# NumPy Arrays

In [ ]:
import tensorflow as tf


In [ ]:
tf.__version__

'2.8.2'

In [ ]:
import numpy as np

In [ ]:
mylist=[1,2,3]
np.array(mylist) # will print


array([1, 2, 3])

In [ ]:
nested_list=[[1,2],[3,4],[5,6]]
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.arange(0,10) # upto 10 not including it

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3) # when we'll use pandas everything will automatically be converted into floating point precision numbers insead of integers

array([0., 0., 0.])

In [ ]:
np.zeros((4,4)) # ((rows.columns))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,3) # gives 3 evenly spaced numbers including 0 and 10

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2) #columns , rand() gives uniform random numbers between [0,1)

array([0.43419416, 0.82551386])

In [ ]:
np.random.rand(3,4)  # rows,columns

array([[0.11827351, 0.49959382, 0.71817399, 0.06210001],
       [0.08633446, 0.98493268, 0.65821931, 0.87877406],
       [0.81626276, 0.78104916, 0.7594822 , 0.99410017]])

In [ ]:
np.random.randn(5,5) # standard normal distribution, mean 0 s.d. 1

array([[ 0.17649984,  0.61466721,  0.6463766 , -1.39243199, -1.58119091],
       [-0.56499051, -0.15231017, -1.17591279,  0.44643074,  1.07591488],
       [ 0.15840017, -1.00300963,  1.29630635, -0.10188821, -2.01754544],
       [ 0.84315001,  0.99232196,  0.05167876, -1.38695139, -0.05332237],
       [ 1.58749051,  2.48254884,  0.41103094, -0.01258067,  1.33400554]])

In [ ]:
np.random.randint(1,100)

16

In [ ]:
np.random.randint(1,100,10)  

array([17, 40, 49, 54, 22, 25, 91, 94, 76,  5])

In [ ]:
np.random.randint(1,100,(2,3))

array([[30, 62, 50],
       [91, 55, 26]])

In [ ]:
# .seed() - Can be used to set the random state, so that the same random
#           result can be generated again and again
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr = np.arange(25) #assign or else won't save permanently
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max()

43

In [ ]:
ranarr.argmax() #location of maximum value in the array

3

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmin()

1

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
ranarr.dtype

dtype('int64')

# Numpy Indexing and Selection

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5] #same as arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
# broadcasting-
# numpy arrays differ from normal py lists because of this ability to
# broadcast with lists. in normal py you can only reassign parts of list
# with new parts of the same shape and size. in numpy you can broadcast
# values to a larger set of values.

In [ ]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr=np.arange(0,11)

In [ ]:
slice_of_arr=arr[0:5]

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:]=99 # [:] for selecting all

In [ ]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:]=100

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Conditional Selection

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

In [ ]:
#list
l=[1,2,3]
a=[1,2,3]
l=l+a #in list it concatenates, in arrays it adds individual element ,sum
l

[1, 2, 3, 1, 2, 3]

In [ ]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# in py
1/0 # = error

ZeroDivisionError: ignored

In [ ]:
# but in numpy arr
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also a warning (but not an error) relating to infinity
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
# Universal array functions
# NumPy comes with many universal array functions, or 
# ufuncs, which are essentially just mathematical operations that
# can be applied across the array.

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.max()

9

In [ ]:
arr.var()

8.25

In [ ]:
arr.std()

2.8722813232690143

In [ ]:
#Axis

In [ ]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [ ]:
arr_2d.shape

(3, 4)

In [ ]:
# sum across columns
arr_2d.sum(axis=1)

array([10, 26, 42])